### PR TITLE
Try to mimic cmake generator (an others)

### PR DESCRIPTION
**Pull request by menuet**
In generated file jamroot, define _GLIBCXX_USE_CXX11_ABI accordingly to compiler.libcxx's value.

Note: my knowledge of b2 is limited. I am not sure I wrote the right fix.

### CODE REVIEW

**Comment by solvingj** [comment]
Fantastic explanation.  If others agree, then we should open ticket to document how to set via profile in Conan docs.

**Comment by lasote** [comment]
Thanks @grafikrobot for the information.We need to think about it (I personally  need to understand it better and play with it) and then decide if/how we change the build helpers to both support all modes without breaking the current default behavior. I'm opening an issue in the Conan repo.

**Comment by lasote** [comment]
By the way, if it is affecting directly to the ABI compatibility it might be something more than an environment variable in a profile. Probably a subsetting. We have to think about it.

**Comment by lasote** [comment]
I commented in the related issue. Reading and recalling all this I think we probably are not doing it wrong. We are modeling the two ABI modes with the libstdc++ and libstdc++11 values of compiler.libcxx setting.

**Comment by solvingj** [comment]
@lasote so what is the interaction between the two?  (the general case of `compiler.libcxx` setting and the specific `_GLIBCXX_USE_CXX11_ABI` flag.  Do you have a feeling about how we should handle it at this point, or do we need more discussion/analysis?

**Comment by lasote** [comment]
The interaction between the setting `compiler.libcxx` and the `_GLIBCXX_USE_CXX11_ABI` flag is the described in the current PR. The user has to decide which ABI uses using that setting. So for me, unless I didn't understand it well, Conan is correct and indeed the current PR.
We could investigate if the use of `--disable-libstdcxx-dual-abi and/or --with-default-libstdcxx-abi` provides any difference, probably it's more correct, but it's working as we expect so it's ok for me.

**Comment by menuet** [comment]
Some context about how I found the problem:
- I made a sample program using
    - the settings **compiler=gcc**, **compiler.libcxx=libstdc++**, **compiler.version=5.4**
    - the dependency **boost_filesystem/1.66.0@bincrafters/testing**
    - and the generator **cmake**
- *boost_filesystem* was then built with **_GLIBCXX_USE_CXX11_ABI=1** (the default gcc value, because conan-boost_generator does not set it to 0)
- *my program* was built with a cmake file that calls conan_basic_setup, which calls conan_set_libcxx, which sets **_GLIBCXX_USE_CXX11_ABI=0** (because cmake generator sets it to 0)
- **my program** crashes because it creates some old-abi string and passes it to boost::filesystem::path which expects a new-abi string.

This seems a problem that may happen as soon as we use gcc 5.x + conan + boost + cmake.

And maybe some other generators have the same issue as boost_generator. So maybe we should review all the other generators in order to be sure that they all set **_GLIBCXX_USE_CXX11_ABI** accordingly to **compiler.libcxx** in the same way as the **cmake generator**.
In the conan sources, I greped _GLIBCXX_USE_CXX11_ABI and could only find the equivalent code in **autotools_environment.py**, but I am not enough familiar with conan sources and separate repos to know where to search exactly.

**Comment by mropert** [comment]
To me all generators should translate settings into compilers toggles the same way else we'll get lots of issues.
I'd go even further and say that we should factorize any code that generates compile flags from settings and then use that input for each generator.
That way we can be consistent if we decide to change something.
That goes for `compiler.libcxx` as well as for `arch` (which sets `-m32` or `-m64`).

**Comment by SSE4** [comment]
so far, my understanding is that **compiler.libcxx** setting actually models 3 orthogonal things at time (as for conan 1.0.4):

- C++ standard library (like _libc++_ VS _libstdc++_, or **-stdlib** compiler flag)
- libstdc++ ABI (which is that **_GLIBCXX_USE_CXX11_ABI** controls)
- C++ standard (which is not actually controlled, because it's different compiler flag **-std**, but name **libstdc++11** suggests this)
that causes a lot of confusion, misunderstanding and debates. the fact that setting is not well documented only makes everything worse, and confusing name forces people to misunderstand and misuse it.

so, my suggestion is to split this setting into 3 different settings, let's name em _cxxstdlib_, _cxxstandard_ and _libstdcxxabi_ (the latter applies only to libstdc++, obviously)
but what should we do with numerous existing packages and recipes, and the fact that conan 1.0 must maintain backward compatibility and avoid breaking changes as much as possible?

I suggest to use **settings preprocessor** for that (the same entity which automatically defines compiler.runtime for Visual Studio) - settings preprocessor can convert legacy **libcxx** setting to the corresponding values of 3 new settings suggested.
that way direct usage of **libcxx** will be still supported, but strongly discouraged for new recipes (conan may produce some human-readable warning).

the next step, is implementing helpers to abstract compiler specific details, so recipe and generator authors can re-use the same codebase to convert high-level conan settings to low-level compiler flags to be passed directly into build systems. PR #2424 basically implements this idea.

**Comment by lasote** [comment]
> so far, my understanding is that compiler.libcxx setting actually models 3 orthogonal things at 
time (as for conan 1.0.4):
>  - C++ standard library (like libc++ VS libstdc++, or -stdlib compiler flag)
> - libstdc++ ABI (which is that _GLIBCXX_USE_CXX11_ABI controls)

True, the second case only for GCC and new ABI we have the libstdc++11, that it is actually the standard libstdc++ but with the new ABI. There is no such mess with it in my opinion. Conceptually could be considered a different standard lib.

> - C++ standard (which is not actually controlled, because it's different compiler flag -std, but name libstdc++11 suggests this)

False, the C++ standard is not adjusted/modeled anywhere. There are some opened PRs to model it but still we have not found a good approach. There are many implications in terms of compatibility with current packages etc and no perfect solution so far.

About your approach, I think @memsharded already answered in the Conan repo, but it is not that simple as split it into 3 different settings, you will, first breaking all the current packages IDs, second breaking the recipes. And I think it is not more clear, honestly.

**Comment by menuet** [comment]
Everybody, do we agree, at least, that the current recipe of boost_generator is broken ?
We should at least fix it in the short term with something like my proposed patch (and later we can think about clean separations of concerns of settings).
As I am not enough expert with b2/conan in order to know if my patch is ok, can someone review it?

**Comment by lasote** [comment]
I think it is ok (on the part related with conan)

**Comment by SSE4** [comment]
new PR accumulated this: https://github.com/bincrafters/conan-boost_generator/pull/6, closing

**Pull request closed without merging**
